### ISSUE TITLE
Support for languages other than Mandarin

### ISSUE THREAD

**Issue by flexthink** [mccj/Hangfire.Dashboard.Management#1]
The default implementation of `CustomHangfireLanguage` appears to be translating everything into Mandarin in a hard-coded fashion (using if-else-if-else). The main README page has screenshots in English. Is there an easy way to switch the extension to English without making translation completely custom?

**Comment by staticdev** [comment]
I also have the same problem.. Hangfire becomes in Mandarim. Couldn't it be default to English and customized?

**Comment by mccj** [comment]
```C#
GlobalConfiguration.Configuration
    .UseManagementPages(config => {
        return config
            .AddJobs(< assembly with IJob implementations >)
            .SetCulture(new System.Globalization.CultureInfo("en-us"))
            //.TranslateJson(< Custom language JSON >)
            ////or
            //.TranslateCulture(< Custom Language Object >)
            ////or
            //.TranslateStream(< Custom language Stream >);
            ;
    });   
```
