### ISSUE TITLE
Target .NETFramework 4.6.0

### ISSUE THREAD

**Issue by SacuL** [mccj/Hangfire.Dashboard.Management#7]
Hello,

Congrats on your project, looks really useful.
I've checked the nuget page and it seems it builds for .NETFramework 4.6.1.
Any chance to build for .NETFramework 4.6.0 as well ?

**Comment by mccj** [comment]
1.7.9.1-beta-1 supported

**Comment by SacuL** [comment]
It works!
Just added to my project and it's running fine with my previous jobs.
I haven't added any custom IJob classes/Pages yet, so the /management page is empty. I will try that later.

Thank you!
